server:
  port: 8088

spring:
  application:
    name: user-service
  datasource:
    # url: jdbc:h2:mem:user-service-db;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:file:C:/data/sample 
    username: root
    password: root
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true